name: Push to nuget feed on release

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [regress_update]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nuget
        uses: nuget/setup-nuget@v1
      
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '0 month'

      - name: Download artifact
        #src: https://github.com/marketplace/actions/download-workflow-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.dll_pat }}
          workflow: build.yml
          branch: master
          path: .
          repo: TaleSpire-Modding/AutomationDlls

      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '0 month'
          
#       - name: build
#         run: dotnet build

#       - uses: actions/upload-artifact@v2
#         with:
#           name: ConfigurationManager.dll
#           path: ConfigurationManager\bin\Debug\ConfigurationManager.dll

#       - name: List
#         run: |
#           cd artifacts
#           dir
